//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoSystemVersions.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfoSystemVersions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1613304550_193_p_sinii_obemnii_fon_243 {
            get {
                object obj = ResourceManager.GetObject("1613304550_193-p-sinii-obemnii-fon-243", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1636390141_74_bigfoto_name_p_neitralnii_sinii_fon_81 {
            get {
                object obj = ResourceManager.GetObject("1636390141_74-bigfoto-name-p-neitralnii-sinii-fon-81", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1636390141_74_bigfoto_name_p_neitralnii_sinii_fon_811 {
            get {
                object obj = ResourceManager.GetObject("1636390141_74-bigfoto-name-p-neitralnii-sinii-fon-811", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1644923633_1_www_funnyart_club_p_avp_fon_krasivo_1 {
            get {
                object obj = ResourceManager.GetObject("1644923633_1-www-funnyart-club-p-avp-fon-krasivo-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1660129053_26_kartinkin_net_p_goluboi_fon_karandashom_krasivo_27 {
            get {
                object obj = ResourceManager.GetObject("1660129053_26-kartinkin-net-p-goluboi-fon-karandashom-krasivo-27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1666158767_61_mykaleidoscope_ru_p_belii_kamuflyazh_oboi_66 {
            get {
                object obj = ResourceManager.GetObject("1666158767_61-mykaleidoscope-ru-p-belii-kamuflyazh-oboi-66", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1666402169_4_mykaleidoscope_ru_p_krasno_oranzhevii_krasivo_4 {
            get {
                object obj = ResourceManager.GetObject("1666402169_4-mykaleidoscope-ru-p-krasno-oranzhevii-krasivo-4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9254b9ea68eca665627f4aec16527d7a {
            get {
                object obj = ResourceManager.GetObject("9254b9ea68eca665627f4aec16527d7a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap counter_strike_counter_strike_global_offensive_awp_azimov_guns_dragon_lore_counter_strike_wallpaper_9950284d414a1d8b0607c85f00d1a65d {
            get {
                object obj = ResourceManager.GetObject("counter-strike-counter-strike-global-offensive-awp-azimov-guns-dragon-lore-counte" +
                        "r-strike-wallpaper-9950284d414a1d8b0607c85f00d1a65d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f08371b6_4ece_48c7_89c6_df23be1ff096_1613149535430 {
            get {
                object obj = ResourceManager.GetObject("f08371b6-4ece-48c7-89c6-df23be1ff096_1613149535430", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maxresdefault__1_ {
            get {
                object obj = ResourceManager.GetObject("maxresdefault (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sinij_fon_s_volnistym_svecheniem {
            get {
                object obj = ResourceManager.GetObject("sinij-fon-s-volnistym-svecheniem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
